service: airtable-backend

provider:
  name: aws
  runtime: nodejs10.x

functions:
  register:
    handler: index.register
    events:
      - http:
          path: register
          method: post
          cors: true
